#!/usr/bin/env bash
set -euo pipefail

# bookmark-to-obsidian: Interactive Setup
# Guides you through creating config.yaml on first run.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_OUT="$SCRIPT_DIR/config.yaml"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║     bookmark-to-obsidian setup wizard       ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Check existing config ─────────────────────────────────
if [ -f "$CONFIG_OUT" ]; then
  echo "config.yaml already exists at: $CONFIG_OUT"
  read -rp "Overwrite? [y/N] " overwrite
  if [[ "${overwrite,,}" != "y" ]]; then
    echo "Setup cancelled. Edit config.yaml manually if needed."
    exit 0
  fi
fi

# ── Check dependencies ────────────────────────────────────
echo "Checking dependencies..."

check_dep() {
  local cmd="$1" install_hint="$2"
  if command -v "$cmd" &>/dev/null; then
    echo "  ✓ $cmd"
  else
    echo "  ✗ $cmd — not found"
    echo "    Install: $install_hint"
    MISSING_DEPS=true
  fi
}

MISSING_DEPS=false
check_dep python3  "https://python.org/downloads"
check_dep curl     "brew install curl  (or apt install curl)"

# Check PyYAML
if python3 -c "import yaml" 2>/dev/null; then
  echo "  ✓ PyYAML"
else
  echo "  ✗ PyYAML — not found"
  read -rp "  Install PyYAML now? [Y/n] " install_yaml
  if [[ "${install_yaml,,}" != "n" ]]; then
    pip3 install pyyaml && echo "  ✓ PyYAML installed"
  else
    echo "  Run: pip3 install pyyaml"
    MISSING_DEPS=true
  fi
fi

if [ "$MISSING_DEPS" = true ]; then
  echo ""
  echo "Some dependencies are missing. Install them and re-run setup.sh."
  exit 1
fi

echo ""

# ── Vault path ────────────────────────────────────────────
echo "── Obsidian Vault ────────────────────────────────────"
echo ""
while true; do
  read -rp "Path to your Obsidian vault root: " vault_path_raw
  vault_path="${vault_path_raw/#\~/$HOME}"
  if [ -d "$vault_path" ]; then
    echo "  ✓ Found vault at: $vault_path"
    break
  else
    echo "  Directory not found: $vault_path"
    read -rp "  Create it? [y/N] " create_vault
    if [[ "${create_vault,,}" == "y" ]]; then
      mkdir -p "$vault_path"
      echo "  ✓ Created: $vault_path"
      break
    fi
  fi
done

# ── Notes subfolder ───────────────────────────────────────
echo ""
read -rp "Notes subfolder inside vault [default: Resources]: " notes_folder
notes_folder="${notes_folder:-Resources}"

# ── Default category ──────────────────────────────────────
echo ""
read -rp "Default category for uncategorized tweets [default: Inbox]: " default_category
default_category="${default_category:-Inbox}"

# ── Bookmarks directory ───────────────────────────────────
echo ""
echo "── Bookmarks ─────────────────────────────────────────"
echo ""
read -rp "Bookmarks directory [default: ~/Documents/twitter-bookmarks]: " bm_dir_raw
bm_dir_raw="${bm_dir_raw:-~/Documents/twitter-bookmarks}"
bm_dir="${bm_dir_raw/#\~/$HOME}"
mkdir -p "$bm_dir"
echo "  ✓ Bookmarks directory: $bm_dir"

# ── Write config.yaml ─────────────────────────────────────
echo ""
echo "── Writing config.yaml ───────────────────────────────"
echo ""

cat > "$CONFIG_OUT" << YAML
# bookmark-to-obsidian configuration
# Generated by setup.sh on $(date +%Y-%m-%d)

vault:
  path: "$vault_path_raw"
  notes_folder: "$notes_folder"
  default_category: "$default_category"

bookmarks:
  dir: "$bm_dir_raw"
  file: "bookmarks.txt"
  processed_file: "bookmarks-processed.txt"

processing:
  batch_size: 10
  batch_delay_seconds: 2

categories:
  - name: "AI Tools"
    keywords:
      - "open-source"
      - "cli"
      - "api"
      - "github"
      - "tool"
      - "library"
      - "sdk"

  - name: "Web Development"
    keywords:
      - "react"
      - "nextjs"
      - "typescript"
      - "javascript"
      - "frontend"

  - name: "AI Research"
    keywords:
      - "paper"
      - "arxiv"
      - "research"
      - "benchmark"
      - "model"
      - "llm"

# Add your own categories — see config.example.yaml for more examples.

wikilinks: {}
# Add vault entity names to auto-link, e.g.:
# "My Project": "[[My Project]]"

enrichment:
  enabled: true
  max_links_per_note: 3

template:
  base_tags:
    - "type/tweet"
    - "source/twitter"
  include_engagement: true
  include_my_notes: true
  distillation_start: 0
YAML

echo "  ✓ Written: $CONFIG_OUT"

# ── Optional: Playwright setup ────────────────────────────
echo ""
echo "── Automated Extraction (optional) ──────────────────"
echo ""
echo "Automated extraction uses Playwright to scroll your bookmarks"
echo "automatically — no browser console needed."
echo ""
echo "Requires: Node.js + npm install (about 100MB for Playwright)"
echo ""
read -rp "Set up automated extraction now? [y/N] " setup_playwright
if [[ "${setup_playwright,,}" == "y" ]]; then
  if ! command -v node &>/dev/null; then
    echo "  ✗ Node.js not found."
    echo "    Install: https://nodejs.org"
  elif ! command -v npm &>/dev/null; then
    echo "  ✗ npm not found (should come with Node.js)."
  else
    echo "  Installing Playwright..."
    (cd "$SCRIPT_DIR" && npm install) && echo "  ✓ Playwright installed"
    echo ""
    echo "  Next step: export your X.com session cookies."
    read -rp "  Run cookie export now? [Y/n] " run_cookies
    if [[ "${run_cookies,,}" != "n" ]]; then
      bash "$SCRIPT_DIR/scripts/export-cookies.sh" --output "$SCRIPT_DIR/cookies.json"
    else
      echo "  Run later: ./bookmark-to-obsidian cookies"
    fi
  fi
fi

# ── Done ──────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════╗"
echo "║  Setup complete! Here's how to use it:   ║"
echo "╚══════════════════════════════════════════╝"
echo ""
if [ -f "$SCRIPT_DIR/cookies.json" ]; then
  echo "  Automated extraction is ready:"
  echo "    ./bookmark-to-obsidian         # Full pipeline (extract + process)"
  echo "    ./bookmark-to-obsidian extract # Just pull bookmarks"
  echo "    ./bookmark-to-obsidian process # Just process into notes"
else
  echo "  Manual extraction (browser console):"
  echo "    1. ./bookmark-to-obsidian extract"
  echo "       # Pastes script in browser console at x.com/i/bookmarks"
  echo "    2. ./bookmark-to-obsidian extract --save  (after console finishes)"
  echo "    3. ./bookmark-to-obsidian process"
  echo ""
  echo "  Or set up automated extraction later:"
  echo "    ./bookmark-to-obsidian cookies"
fi
echo ""
echo "  Edit config.yaml any time to change folders, categories, or wikilinks."
echo "  See config.example.yaml for full documentation of all options."
echo ""
